import { PurchaseOrderPdfLabels } from './purchase-order-pdf-labels';

export const PURCHASE_ORDER_PDF_LABELS_EN: PurchaseOrderPdfLabels = {
  originalDocumentTitle: 'Original request document',
  purchaseOrderTitle: 'PURCHASE ORDER',
  folioPrefix: 'Folio',
  receptionDocumentTitle: 'Receipt voucher',
  summary: 'Summary',
  creationDate: 'Creation date',
  createdBy: 'Created by',
  expectedDate: 'Expected date',
  status: 'Status',
  payment: 'Payment',
  receptionDate: 'Receipt date',
  vendor: 'Vendor',
  rfcPrefix: 'Tax ID',
  addressPrefix: 'Address',
  destinationWarehouse: 'Destination warehouse',
  branchPrefix: 'Branch',
  requestedProductsDetail: 'Requested products detail',
  receivedProductsDetail: 'Received products detail',
  product: 'Product',
  requestedQty: 'Qty. requested',
  receivedBatches: 'Received batches',
  receivedQty: 'Qty. received',
  unitPrice: 'Unit price',
  lineAmount: 'Amount',
  total: 'Total',
  unitPrefix: 'Unit',
  modePrefix: 'Mode',
  noTag: 'No tag',
  measurePrefix: 'measure',
  noBatchesRegistered: 'No batches registered',
  notesPrefix: 'Notes',
  notesEmpty: 'No notes',
  pageLabel: 'Page',
  subtotal: 'Subtotal',
  vat: 'VAT',
  ieps: 'IEPS',
  totalLabel: 'TOTAL',
  currency: 'Currency',
  statusCreated: 'Created',
  statusReceived: 'Received',
  statusCancelled: 'Cancelled',
  paymentPending: 'Pending',
  paymentPaid: 'Paid',
  dateLocale: 'en-US',
};
