import { PurchaseOrderPdfLabels } from './purchase-order-pdf-labels';

export const PURCHASE_ORDER_PDF_LABELS_ES: PurchaseOrderPdfLabels = {
  originalDocumentTitle: 'Documento original de solicitud',
  purchaseOrderTitle: 'ORDEN DE COMPRA',
  folioPrefix: 'Folio',
  receptionDocumentTitle: 'Comprobante de recepción',
  summary: 'Resumen',
  creationDate: 'Fecha de creación',
  createdBy: 'Creado por',
  expectedDate: 'Fecha esperada',
  status: 'Estado',
  payment: 'Pago',
  receptionDate: 'Fecha de recepción',
  vendor: 'Proveedor',
  rfcPrefix: 'RFC',
  addressPrefix: 'Dirección',
  destinationWarehouse: 'Almacén destino',
  branchPrefix: 'Sucursal',
  requestedProductsDetail: 'Detalle de productos solicitados',
  receivedProductsDetail: 'Detalle de productos recibidos',
  product: 'Producto',
  requestedQty: 'Cant. solicitada',
  receivedBatches: 'Lotes ingresados',
  receivedQty: 'Cant. recibida',
  unitPrice: 'Precio Unit.',
  total: 'Total',
  unitPrefix: 'Unidad',
  modePrefix: 'Modo',
  noTag: 'Sin tag',
  noBatchesRegistered: 'Sin lotes registrados',
  notesPrefix: 'Notas',
  notesEmpty: 'Sin notas',
  pageLabel: 'Página',
  subtotal: 'Subtotal',
  vat: 'IVA',
  ieps: 'IEPS',
  totalLabel: 'TOTAL',
  statusCreated: 'Creada',
  statusReceived: 'Recibida',
  statusCancelled: 'Cancelada',
  paymentPending: 'Pendiente',
  paymentPaid: 'Pagado',
  dateLocale: 'es-MX',
};
