-- Verify script - Count paid payments correctly and show regenerated order

-- First: Show paid count per contract
SELECT 
  c.contract_number,
  c.contract_date,
  c.payment_months,
  COUNT(p.id) as total_payments_in_db,
  SUM(CASE WHEN p.status = 'pagado' THEN 1 ELSE 0 END) as paid_count_in_db
FROM contracts c
LEFT JOIN payments p ON c.id = p.contract_id
WHERE c.status = 'activo'
GROUP BY c.id, c.contract_number, c.contract_date, c.payment_months
ORDER BY c.contract_number;

-- Second: Show how regenerated payments would look (with correct paid count)
SELECT 
  c.contract_number,
  c.contract_date,
  seq.num as payment_number,
  DATE(CONCAT(
    YEAR(DATE_ADD(DATE(CONCAT(YEAR(c.contract_date), '-', MONTH(c.contract_date), '-01')), INTERVAL (seq.num - 1) MONTH)),
    '-',
    MONTH(DATE_ADD(DATE(CONCAT(YEAR(c.contract_date), '-', MONTH(c.contract_date), '-01')), INTERVAL (seq.num - 1) MONTH)),
    '-05'
  )) as new_payment_date,
  CASE 
    WHEN seq.num <= (
      SELECT COUNT(*) FROM payments p2 
      WHERE p2.contract_id = c.id AND p2.status = 'pagado'
    ) THEN 'pagado'
    ELSE 'pendiente'
  END as new_status
FROM contracts c
CROSS JOIN (
  SELECT 1 as num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
  UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
  UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
  UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
  UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
  UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
  UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
  UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
  UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
  UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55
  UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60
  UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65
  UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70
  UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75
  UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80
  UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85
  UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90
  UNION SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95
  UNION SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100
  UNION SELECT 101 UNION SELECT 102 UNION SELECT 103 UNION SELECT 104 UNION SELECT 105
  UNION SELECT 106 UNION SELECT 107 UNION SELECT 108 UNION SELECT 109 UNION SELECT 110
  UNION SELECT 111 UNION SELECT 112 UNION SELECT 113 UNION SELECT 114 UNION SELECT 115
  UNION SELECT 116 UNION SELECT 117 UNION SELECT 118 UNION SELECT 119 UNION SELECT 120
) seq
WHERE c.status = 'activo'
  AND seq.num <= c.payment_months
ORDER BY c.contract_number, new_payment_date;
