import { SalesOrderPdfLabels } from './sales-order-pdf-labels';

export const SALES_ORDER_PDF_LABELS_ES: SalesOrderPdfLabels = {
  originalDocumentTitle: 'Documento original de orden de venta',
  salesOrderTitle: 'ORDEN DE VENTA',
  deliveryDocumentTitle: 'Comprobante de entrega',
  deliveryTitle: 'ENTREGA',
  folioPrefix: 'Folio',
  summary: 'Resumen',
  creationDate: 'Fecha de creación',
  createdBy: 'Creado por',
  expectedDate: 'Fecha esperada',
  status: 'Estado',
  payment: 'Pago',
  customer: 'Cliente',
  emailPrefix: 'Correo',
  phonePrefix: 'Teléfono',
  sourceWarehouse: 'Almacén origen',
  branchPrefix: 'Sucursal',
  productsDetail: 'Detalle de productos',
  product: 'Producto',
  quantity: 'Cantidad',
  unitPrice: 'Precio Unit.',
  discount: 'Descuento',
  total: 'Total',
  unitPrefix: 'Unidad',
  notesPrefix: 'Notas',
  notesEmpty: 'Sin notas',
  pageLabel: 'Página',
  subtotal: 'Subtotal',
  discountTotal: 'Descuento',
  lineDiscountTotal: 'Desc. por producto',
  globalDiscountTotal: 'Desc. global',
  vat: 'IVA',
  ieps: 'IEPS',
  totalLabel: 'TOTAL',
  statusCreated: 'Creada',
  statusInSelection: 'En Selección',
  statusReadyForDelivery: 'Lista para entrega',
  statusFulfilled: 'Surtida',
  statusCancelled: 'Cancelada',
  paymentPending: 'Pendiente',
  paymentPaid: 'Pagado',
  dateLocale: 'es-MX',
};
