import { SalesOrderPdfLabels } from './sales-order-pdf-labels';

export const SALES_ORDER_PDF_LABELS_EN: SalesOrderPdfLabels = {
  originalDocumentTitle: 'Original sales order document',
  salesOrderTitle: 'SALES ORDER',
  folioPrefix: 'Folio',
  summary: 'Summary',
  creationDate: 'Creation date',
  createdBy: 'Created by',
  expectedDate: 'Expected date',
  status: 'Status',
  payment: 'Payment',
  customer: 'Customer',
  emailPrefix: 'Email',
  phonePrefix: 'Phone',
  sourceWarehouse: 'Source warehouse',
  productsDetail: 'Products detail',
  product: 'Product',
  quantity: 'Quantity',
  unitPrice: 'Unit price',
  discount: 'Discount',
  total: 'Total',
  unitPrefix: 'Unit',
  notesPrefix: 'Notes',
  subtotal: 'Subtotal',
  discountTotal: 'Discount',
  lineDiscountTotal: 'Product discounts',
  globalDiscountTotal: 'Global discount',
  vat: 'VAT',
  ieps: 'IEPS',
  totalLabel: 'TOTAL',
  statusCreated: 'Created',
  statusInSelection: 'In selection',
  statusReadyForDelivery: 'Ready for delivery',
  statusFulfilled: 'Fulfilled',
  statusCancelled: 'Cancelled',
  paymentPending: 'Pending',
  paymentPaid: 'Paid',
  dateLocale: 'en-US',
};
